### ISSUE TITLE
Refactor the dcmparser module

### ISSUE THREAD

**Issue by neandrake** [neandrake/dicom-pipe#2]
The dicom parser (`dcmpipe_lib/src/core/dcmparser.rs`) is a giant file clocking in at over 1k lines, and it contains a few extra structs (like the errors, parser-builder, iterator implementation, and dataset wrapper modules). I think it would make sense to split this out into a separate module to keep the code manageable. 

I think we could take `dcmparser.rs` and `dcmparser_util.rs` and move them into their own separate module simply called `parser`:
```
/core/parser/mod.rs -- this file should only re-expose things in the module to be public
/core/parser/builder.rs -- move the parser builder to its own file
/core/parser/dataset.rs -- the dataset wrapper modules can be moved here
/core/parser/error.rs -- move the error type to its own file
/core/parser/iter.rs -- the implementation of Iter<> could move to its own file
/core/parser/parser.rs -- the parser struct + impl
/core/parser/util.rs -- move the dcmparser_util.rs into here
```

The `parser.rs` file would probably still be nearly 1k lines but I think pulling out all the extra structs/impls would make it more easily digested.

**Comment by chafey** [comment]
Just submitted a PR for this, let me know what you think

**Comment by neandrake** [comment]
All planned changes are done
