### ISSUE TITLE
Simplify Getting Started

### ISSUE THREAD

**Issue by chafey** [neandrake/dicom-pipe#3]
I just pulled the repository, ran cargo test and it failed due to what looks like missing test data.  Digging deeper I see that I need to download test data into dcmpipe_tests/fixtures but it isn't clear what I need to download, especially from David Clunie's web site.  This is going to discourage new users from engaging with the project as they won't be able to get a clean build right away.  Is there a reason you don't want to check the test images into the repo itself?  If the images are too large, find or create smaller ones using gdcm or dcmtk.

**Comment by neandrake** [comment]
Shoot I thought there was a publicly accessible link to download a zip of the test image sets. The download is ~700mb so it's quite large so I did not want to include them in the repository. Let me see if I can upload it to Google Drive or similar.

I would ideally like to craft specific unit test datasets however I wasn't sure the best way to go about doing that.

**Comment by chafey** [comment]
I was able to download the gdcm ones, but David Clunie's site has several links to images in the "Images" section - do I need to download all of them?

**Comment by chafey** [comment]
Also - I think it is good to have unit tests inline in the source files that don't have dependencies on actual dicom files - everything is created/built on the fly in the unit tests.  Actual testing of DICOM files can be done via integration tests in a tests folder.  I took this approach with the RLE Decoder and like how it turned out

**Comment by neandrake** [comment]
From David Clunie's site I believe I downloaded anything which still had a valid link (not all of them did). I believe the primary datasets from his site are the "Internationalized character set test DICOM images".

The tests which rely on dicom files expect them to be in a specific layout relative to the `dcmpipe_tests` folder. The attachment (uploading to Google Drive) should just need downloaded into the `dcmpipe_tests` folder and extracted there - it should create a `fixtures` folder and everything should be in the right location. I have tested this procedure setting up another workstation so there will hopefully not be too many other difficulties.

I agree it makes sense to inline unit tests however I found a lot of the tests I started putting together ended up adding a lot of additional code into the file which I found made navigating the files more difficult. I'm open to restructuring these, particularly as I think it is more idiomatic rust to have unit tests right inline with the code being tested.

**Comment by neandrake** [comment]
Here is the link to download from Google Drive:
https://drive.google.com/file/d/1VI89r3leiLPm9-8sClyy0o15KtGZeqaD/view?usp=sharing

I will update the readme for `dcmpipe_tests` to include this link.

**Comment by neandrake** [comment]
One thing to note about the test fixtures - there are two tests currently marked with `#[ignore]` at the bottom of the parsing tests which recursively walk the `fixtures` folder and attempt to parse all the dicom files including parsing element values. I used these tests to locate data which caused the parser to fail, then typically added those files as individual tests. So there are a great many test files but the written tests don't use all of them -- with exception to the ignored ones which I only turned on temporarily to locate other parsing issues.

**Comment by chafey** [comment]
Just downloaded and ran cargo test but still have 4 failed tests.  Can you double check to make sure all tests pass?

**Comment by neandrake** [comment]
Oh not all tests pass -- having 74 pass, 12 ignored, and 4 failing is expected right now.

These tests are expected to fail right now as they are all testing the same dicom file. This dicom file utilizes multiple character sets when encoding string values and that support is not yet implemented (I need to make a task). Implementing this will likely need to change the API for how characters sets are handled.
- `charsets::test_scs_h32`
- `parsing::test_dicomdir_with_std`
- `parsing::test_dicomdir_withoutstd`

This `parsing::test_unknown_explicit_vr_is_error` is also expected to fail right now as I recently made some changes to not consider an unknown explicit VR as an error. Previously if the explicit VR did not map to a standard VR this would result in an error parsing the element. To allow the parser to be more lenient however it should still be possible to parse the binary stream as the VR only indicates how the element value should be parsed. An invalid VR should not prevent accessing the element or its value as bytes however. The test here needs updated.

**Comment by chafey** [comment]
can we set the failing tests to ignore and create issues to track them?

**Comment by neandrake** [comment]
Yes I think that's a good idea. I added you as collaborator to the project so you should be able to help with setting up tasks and such.

**Comment by neandrake** [comment]
I can create the tasks and change the tests to be ignored but I probably will not be able to get to that until later today or tomorrow. You are welcome to create the tasks for that now if you'd like to get a head start.

**Comment by neandrake** [comment]
I split out the UT failures into #6  and #7 and made commits for the tests to be ignored. A clarification about what I said earlier. I indicated that all 3 tests failing due to #6 are using the same file. That's not actually true -- the `DICOMDIR` tests a different file but it's failing for the same reason. The `DICOMDIR` is a directory listing of the character set files, and includes the patient name which is encoded in the same way, resulting in the same error.
